[[codeprimate-domain]]
= Codeprimate Domain
:version: 0.3.0


The Codeprimate Domain project is a Java library of common Abstract Data Types (ADT), application domain model objects
and entities for recording and processing data in a Java application.

[[requirements]]
== Requirements

1. Baseline is Java SE (JDK/JRE) 17.
2. Built with Oracle JDK 17.0.14 2025-01-21 LTS (build 17.0.14+8-LTS-191).

[[license]]
== License

*Domain* is licensed under the **Apache 2.0 Software License Agreement**.

[[download]]
== Download / Include

.Maven
====
[source,xml]
[subs="verbatim,attributes"]
----
<dependency>
  <groupId>org.codeprimate.domain</groupId>
  <artifactId>cp-domain</artifactId>
  <version>{version}</version>
</dependency>
----
====

[[issues]]
== Issues

Please use https://github.com/codeprimate-software/cp-domain/issues[GitHub Issues] to report any bugs, improvements
or feature requests.

[[contributions]]
== Contributions

Thank you for your interests in contributing to the *Codeprimate Build* project.  A full *contributor license agreement*
(CLA) along with details on how to contribute to this project will be provided shortly.

In the meantime, please submit tickets using https://github.com/codeprimate-software/cp-domain/issues[GitHub Issues]
or PRs using https://github.com/codeprimate-software/cp-domain/pulls[GitHub Pull Requests].

**Thank you!**
